name: Auto_ForkFull
on:
  schedule:
    - cron: '10 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-auto-forkfull
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync rpgrpg-qlfreenom
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/rpgrpg/freenom-qinglong.git"
          source_branch: "main"
          destination_branch: "ql_freenom"
          github_token: ${{ secrets.PAT }}

      - name: sync alist-org-alist
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/alist-org/alist.git"
          source_branch: "main"
          destination_branch: "alist"
          github_token: ${{ secrets.PAT }}
          
      - name: sync vaxilu-x-ui
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/vaxilu/x-ui.git"
          source_branch: "main"
          destination_branch: "x-ui"
          github_token: ${{ secrets.PAT }}
          
      - name: sync luolongfei-freenom
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/luolongfei/freenom.git"
          source_branch: "main"
          destination_branch: "freenom"
          github_token: ${{ secrets.PAT }}
        
      - name: sync BookerLiu-GeekDesk
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/BookerLiu/GeekDesk.git"
          source_branch: "master"
          destination_branch: "GeekDesk"
          github_token: ${{ secrets.PAT }}
          
      - name: sync sml2h3-ast_tools
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/sml2h3/ast_tools.git"
          source_branch: "main"
          destination_branch: "ast_tools"
          github_token: ${{ secrets.PAT }}
